# **Pra Pengolahan Data**

# Langkah 1 - Import Library

In [10]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Langkah 2 - Load Data

In [11]:
dataset = pd.read_csv('data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
# Mengambil data kolom ke3 sampai sebelum terakhir
y = dataset.iloc[:, -1].values
# Mengambil data kolom terakhir

In [12]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


# Langkah 3 - Encoding Data Kategorikal

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
# Encoding kolom ke-3

In [14]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')   
# ColumnTransformer digunakan untuk menerapkan pengkodean ke kolom tertentu, sementara kolom lainnya dibiarkan tidak berubah.
# OneHotEncoder untuk mengubah kolom 'Geography' (kolom ke-1) menjadi representasi biner
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Langkah 5 - Split Data

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Langkah 6 - Scaling Fitur

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Membuat Model ANN**

# Langkah 1 - Inisiasi Model ANN

In [19]:
ann = tf.keras.models.Sequential()

# Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Hidden layer dengan 6 neuron

# Langkah 3 - Membuat Hidden Layer Kedua

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Langkah 4 - Membuat Output Layer

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **Training Model**

# Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Langkah 2 - Fitting Model

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
# batch_size = Jumlah sample/data yang digunakan

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7974 - loss: 0.5408
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7992 - loss: 0.4706
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7942 - loss: 0.4544
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7987 - loss: 0.4387
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7972 - loss: 0.4367
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7941 - loss: 0.4310
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7987 - loss: 0.4302
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7970 - loss: 0.4324
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4283
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8144 - loss: 0.4246
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8134 - loss: 0.4158
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

# **Membuat Prediksi**

# Modelkan Data Baru dan Buat Prediksi

In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
# mencetak hasil prediksi (apakah lebih dari 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
[[False]]


# Prediksi Dengan Data Testing

In [26]:
y_pred = ann.predict(X_test)
# Hasil prediksinya berupa probabilitas
y_pred = (y_pred > 0.5)
# mengubahnya menjadi nilai true/false
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Cek Akurasi dan Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

# (prediksi benar untuk positif) (prediksi benar untuk negatif)
# (prediksi salah untuk positif) (prediksi salah untuk negatif)

[[1531   64]
 [ 206  199]]


0.865